### ISSUE TITLE
Failed to load OceanToken from main Error: "Cannot find module './OceanToken.main.json'" (and many similar issues)

### ISSUE THREAD

**Issue by mardo** [oceanprotocol/react-tutorial#3]
Hi,

I have downloaded the project and ran:

```
npm install
npm start
```

And got a bunch of errors related to Cannot find module:

<img width="1441" alt="Screen Shot 2019-12-12 at 10 04 38 AM" src="https://user-images.githubusercontent.com/978193/70728414-fa7fc000-1cc6-11ea-9143-496fd976bf89.png">

react-tutorial|master ✗⇒ node -v
v10.16.3
react-tutorial|master ✗⇒ npm -v
6.9.0
Browser: Firefox 71.0

Any help is greatly appreciated!

**Comment by kremalicious** [comment]
By default the react-tutorial connects to our Nile test network. You also have to connect to it in your MetaMask https://docs.oceanprotocol.com/tutorials/connect-to-networks/#connect-to-the-nile-testnet

The errors suggest you are connected to Ethereum Main network in MetaMask so squid-js tries to load all the contracts from it but only the Ocean Token contract is deployed on Ethereum Mainnet

**Comment by mardo** [comment]
Thanks, that did the trick!
