### ISSUE TITLE
how to run this appliction with ocean pacific network

### ISSUE THREAD

**Issue by areaboy** [oceanprotocol/react-tutorial#5]
Please Sir,Am working on ocean pacific app contest at **devpost.com** 

The documentation in the app only shows how to run it in a  Nile network
Eg connecting this link https://nile.dev-ocean.com to RPC in metamask.

My issue is:
please  How do I connect this application to run on Ocean Pacific Network .

Thanks

**Comment by kremalicious** [comment]
take a look at this env var file from Commons to get the correct values for the respective networks: https://github.com/oceanprotocol/commons/blob/master/client/.env.local.example

And then connect in MetaMask to Pacific too
https://docs.oceanprotocol.com/tutorials/connect-to-networks/#connect-to-the-pacific-network

**Comment by areaboy** [comment]
Thanks for responding.

Please Sir, can you help me fix the right url values for the following instances based on pacific ocean network
Am confused of the right url to be put in place in the parameters below

nodeUri: '',
aquariusUri: '',
brizoUri: '',
brizoAddress: '',
secretStoreUri: '',



here is the code

async componentDidMount() {
this.setState({ isLoadingAllForReg: true })
    const ocean = await new Ocean.getInstance({
      web3Provider: web3,
      nodeUri: '',
      aquariusUri: '',
      brizoUri: '',
      brizoAddress: '',
      secretStoreUri: '',
      // local Spree connection
      // nodeUri: 'http://localhost:8545',
      // aquariusUri: 'http://aquarius:5000',
      // brizoUri: 'http://localhost:8030',
      // brizoAddress: '0x00bd138abd70e2f00903268f3db08f2d25677c9e',
      // secretStoreUri: 'http://localhost:12001',
      verbose: true

    })
    this.setState({ ocean })
    console.log('Finished loading contracts.')
    this.setState({ isLoadingAllForReg: false })

 //this.fetchData();
  }




Here is pacific ocean instances

# Connect to Pacific
#
REACT_APP_NODE_URI="https://pacific.oceanprotocol.com"
REACT_APP_SECRET_STORE_URI="https://secret-store.oceanprotocol.com"
REACT_APP_FAUCET_URI="https://faucet.oceanprotocol.com"
# Pacific Test instances
REACT_APP_AQUARIUS_URI="https://aquarius.test.oceanprotocol.com"
REACT_APP_BRIZO_URI="https://brizo.test.oceanprotocol.com"
REACT_APP_BRIZO_ADDRESS="0x0474ed05ba757dde575dfaaaa267d9e7f3643abc"
# Pacific Commons instances
# REACT_APP_AQUARIUS_URI="https://aquarius.commons.oceanprotocol.com"
# REACT_APP_BRIZO_URI="https://brizo.commons.oceanprotocol.com"
# REACT_APP_BRIZO_ADDRESS="0x008c25ed3594e094db4592f4115d5fa74c4f41ea"

Thanks

**Comment by areaboy** [comment]
Thanks for responding.

Please Sir, can you help me fix the right url values for the following instances based on pacific ocean network
Am confused of the right url to be put in place in the parameters below

**nodeUri: '',
aquariusUri: '',
brizoUri: '',
brizoAddress: '',
secretStoreUri: '',**



here is the code

async componentDidMount() {
this.setState({ isLoadingAllForReg: true })
    const ocean = await new Ocean.getInstance({
      web3Provider: web3,
      nodeUri: '',
      aquariusUri: '',
      brizoUri: '',
      brizoAddress: '',
      secretStoreUri: '',
      // local Spree connection
      // nodeUri: 'http://localhost:8545',
      // aquariusUri: 'http://aquarius:5000',
      // brizoUri: 'http://localhost:8030',
      // brizoAddress: '0x00bd138abd70e2f00903268f3db08f2d25677c9e',
      // secretStoreUri: 'http://localhost:12001',
      verbose: true

    })
    this.setState({ ocean })
    console.log('Finished loading contracts.')
    this.setState({ isLoadingAllForReg: false })

 //this.fetchData();
  }




Here is pacific ocean instances

# Connect to Pacific
#
REACT_APP_NODE_URI="https://pacific.oceanprotocol.com"
REACT_APP_SECRET_STORE_URI="https://secret-store.oceanprotocol.com"
REACT_APP_FAUCET_URI="https://faucet.oceanprotocol.com"
# Pacific Test instances
REACT_APP_AQUARIUS_URI="https://aquarius.test.oceanprotocol.com"
REACT_APP_BRIZO_URI="https://brizo.test.oceanprotocol.com"
REACT_APP_BRIZO_ADDRESS="0x0474ed05ba757dde575dfaaaa267d9e7f3643abc"
# Pacific Commons instances
# REACT_APP_AQUARIUS_URI="https://aquarius.commons.oceanprotocol.com"
# REACT_APP_BRIZO_URI="https://brizo.commons.oceanprotocol.com"
# REACT_APP_BRIZO_ADDRESS="0x008c25ed3594e094db4592f4115d5fa74c4f41ea"

Thanks

**Comment by kremalicious** [comment]
just map the env vars from commons to the config values from this repo, so:

```
nodeUri: 'https://pacific.oceanprotocol.com',
aquariusUri: 'https://aquarius.test.oceanprotocol.com',
brizoUri: 'https://brizo.test.oceanprotocol.com',
brizoAddress: '0x0474ed05ba757dde575dfaaaa267d9e7f3643abc',
secretStoreUri: 'https://secret-store.oceanprotocol.com',
```

**Comment by areaboy** [comment]
Thanks alot Sir

**Comment by areaboy** [comment]
please sir do not close this for now incase if i have any issues as submission is just 2 days now. Thanks for your understanding

**Comment by kremalicious** [comment]
Sorry, this is an issue tracker and not a personal support forum. If you have more questions I suggest you ask them on Gitter. If you run into issues with any of our implementations, feel free to open an issue on the respective repo
