### ISSUE TITLE
Is there any API for getting Logged In User Data

### ISSUE THREAD

**Issue by areaboy** [oceanprotocol/react-tutorial#6]
When I logged-In via metamask to nile network, I can immediately start publishing Data. Please Is there any API or whatever that I can used to get my loggedin User data like, email, owner or creator  identity.

For instance when I publish data, I can see my creator or owner id in the json response.

Thanks

**Comment by kremalicious** [comment]
We only use Web3 accounts, meaning Ethereum accounts, to identify users. The account address is the only thing we know about a user. We do not collect email addresses or any other user data. If you want to access a Web3 account, e.g. the ones in MetaMask, you will need to use squid.js's `ocean.accounts` or use web3.js directly.

**Comment by areaboy** [comment]
Thanks for responding Sir. Please  do you have a coding example on getting login users account data whether id, creator id etc so that i can uniquely identify each metamask logged in user. Its urgent. Thanks

**Comment by kremalicious** [comment]
it's all in there in the existing code of this repo, we always have to read out the accounts before doing consume or publish: https://github.com/oceanprotocol/react-tutorial/blob/master/src/index.js#L74

**Comment by areaboy** [comment]
Thanks for responding Sir. So I will find it at this line of code right?

`const accounts = await this.state.ocean.accounts.list()`

**Comment by kremalicious** [comment]
just do `console.log(accounts)` afterwards and see what happens :-) It should return an array of account IDs, and you usually want the first one so just grab this in a next step like `const account = accounts[0]`

**Comment by areaboy** [comment]
its working now. Thanks
